- hosts: cluster
  tasks:
    - name: install cluster packages
      yum: name={{ item }}
      with_items:
        - pacemaker
        - corosync
        - pcs

    - name: setenforce 0
      command: "setenforce 0"
      changed_when: False

    - name: disable selinux
      lineinfile:
        path: "/etc/sysconfig/selinux"
        regexp: "^SELINUX="
        line: "SELINUX=disabled"

    - name: Disable Firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no

    - name: Copy hosts file
      copy:
        src: /ansible/files/hosts
        dest: /etc/hosts
        backup: yes

